"""Add an index on timeline objects.

Revision ID: 6af0357ee34b
Revises: 0df5291d1685
Create Date: 2019-11-05 19:36:32.638086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af0357ee34b'
down_revision = '0df5291d1685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_timeline_user_id', 'user_timeline', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_timeline_user_id', table_name='user_timeline')
    # ### end Alembic commands ###
