"""Use UserTimeline instead of individual models

Revision ID: bab1862ebd29
Revises: de2ba13df54d
Create Date: 2026-04-07 13:28:01.876678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bab1862ebd29'
down_revision = 'de2ba13df54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.drop_constraint('app_glance_slices_app_glance_id_fkey', 'app_glance_slices', type_='foreignkey')
    op.add_column('app_glances', sa.Column('new_id', postgresql.UUID(as_uuid=True), nullable=True))
    conn.execute(sa.text("UPDATE app_glances SET new_id = gen_random_uuid()"))
    op.add_column('app_glance_slices', sa.Column('new_app_glance_id', postgresql.UUID(as_uuid=True), nullable=True))
    conn.execute(sa.text("""
        UPDATE app_glance_slices s
        SET    new_app_glance_id = g.new_id
        FROM   app_glances g
        WHERE  s.app_glance_id = g.id
    """))
    op.drop_column('app_glance_slices', 'app_glance_id')
    op.drop_constraint('app_glances_pkey', 'app_glances', type_='primary')
    op.drop_column('app_glances', 'id')
    op.alter_column('app_glances', 'new_id', new_column_name='id', nullable=False)
    op.alter_column('app_glance_slices', 'new_app_glance_id', new_column_name='app_glance_id')
    op.create_primary_key('app_glances_pkey', 'app_glances', ['id'])
    op.create_foreign_key('app_glance_slices_app_glance_id_fkey', 'app_glance_slices',
                          'app_glances', ['app_glance_id'], ['id'])
    

    op.drop_constraint('timeline_pin_topic_topic_id_fkey', 'timeline_pin_topic', type_='foreignkey')
    op.drop_constraint('timeline_topic_subscriptions_topic_id_fkey', 'timeline_topic_subscriptions', type_='foreignkey')
    op.add_column('timeline_topics', sa.Column('new_id', postgresql.UUID(as_uuid=True), nullable=True))
    conn.execute(sa.text("UPDATE timeline_topics SET new_id = gen_random_uuid()"))
    op.add_column('timeline_pin_topic', sa.Column('new_topic_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('timeline_topic_subscriptions', sa.Column('new_topic_id', postgresql.UUID(as_uuid=True), nullable=True))
    conn.execute(sa.text("""
        UPDATE timeline_pin_topic p
        SET    new_topic_id = t.new_id
        FROM   timeline_topics t
        WHERE  p.topic_id = t.id
    """))
    conn.execute(sa.text("""
        UPDATE timeline_topic_subscriptions s
        SET    new_topic_id = t.new_id
        FROM   timeline_topics t
        WHERE  s.topic_id = t.id
    """))
    op.drop_column('timeline_pin_topic', 'topic_id')
    op.drop_column('timeline_topic_subscriptions', 'topic_id')
    op.drop_constraint('timeline_topics_pkey', 'timeline_topics', type_='primary')
    op.drop_column('timeline_topics', 'id')
    op.alter_column('timeline_topics', 'new_id', new_column_name='id', nullable=False)
    op.alter_column('timeline_pin_topic', 'new_topic_id', new_column_name='topic_id')
    op.alter_column('timeline_topic_subscriptions', 'new_topic_id', new_column_name='topic_id')
    op.create_primary_key('timeline_topics_pkey', 'timeline_topics', ['id'])
    op.create_foreign_key('timeline_pin_topic_topic_id_fkey', 'timeline_pin_topic',
                          'timeline_topics', ['topic_id'], ['id'])
    op.create_foreign_key('timeline_topic_subscriptions_topic_id_fkey', 'timeline_topic_subscriptions',
                          'timeline_topics', ['topic_id'], ['id'])


    op.add_column('timeline_topic_subscriptions', sa.Column('new_id', postgresql.UUID(as_uuid=True), nullable=True))
    conn.execute(sa.text("UPDATE timeline_topic_subscriptions SET new_id = gen_random_uuid()"))
    op.drop_constraint('timeline_topic_subscriptions_pkey', 'timeline_topic_subscriptions', type_='primary')
    op.drop_column('timeline_topic_subscriptions', 'id')
    op.alter_column('timeline_topic_subscriptions', 'new_id', new_column_name='id', nullable=False)
    op.create_primary_key('timeline_topic_subscriptions_pkey', 'timeline_topic_subscriptions', ['id'])


    op.add_column('timeline_topics', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('user_timeline', sa.Column('item_type', sa.String(length=50), nullable=False))
    op.add_column('user_timeline', sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False))
    conn.execute(sa.text("""
        UPDATE user_timeline
        SET    item_type = 'timeline_pins',
               item_id = pin_id
        WHERE  pin_id IS NOT NULL
    """))
    op.drop_index('user_timeline_userid_pinid', table_name='user_timeline')
    op.create_index('user_timeline_userid_itemtype_itemid', 'user_timeline', ['user_id', 'item_type', 'item_id'], unique=True)
    op.drop_constraint('user_timeline_pin_id_fkey', 'user_timeline', type_='foreignkey')
    op.drop_column('user_timeline', 'pin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column('user_timeline', sa.Column('pin_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_timeline_pin_id_fkey', 'user_timeline', 'timeline_pins', ['pin_id'], ['guid'], ondelete='CASCADE')
    conn.execute(sa.text("""
        UPDATE user_timeline
        SET    pin_id = item_id
        WHERE  item_type = 'timeline_pins'
    """))
    op.drop_index('user_timeline_userid_itemtype_itemid', table_name='user_timeline')
    op.create_index('user_timeline_userid_pinid', 'user_timeline', ['user_id', 'pin_id'], unique=False)
    op.drop_column('user_timeline', 'item_id')
    op.drop_column('user_timeline', 'item_type')
    op.drop_column('timeline_topics', 'create_time')

    conn.execute(sa.text("CREATE SEQUENCE tmp_timeline_topic_subscriptions_id_seq"))
    op.add_column('timeline_topic_subscriptions',     sa.Column('new_id', sa.INTEGER(), nullable=True))
    conn.execute(sa.text("UPDATE timeline_topic_subscriptions     SET new_id = nextval('tmp_timeline_topic_subscriptions_id_seq')"))
    op.drop_constraint('timeline_topic_subscriptions_pkey',     'timeline_topic_subscriptions',     type_='primary')
    op.drop_column('timeline_topic_subscriptions',     'id')
    op.alter_column('timeline_topic_subscriptions',     'new_id', new_column_name='id', nullable=False)
    conn.execute(sa.text("ALTER SEQUENCE tmp_timeline_topic_subscriptions_id_seq     OWNED BY timeline_topic_subscriptions.id"))
    conn.execute(sa.text("ALTER TABLE timeline_topic_subscriptions     ALTER COLUMN id SET DEFAULT nextval('tmp_timeline_topic_subscriptions_id_seq')"))
    op.create_primary_key('timeline_topic_subscriptions_pkey',     'timeline_topic_subscriptions',     ['id'])


    op.drop_constraint('timeline_pin_topic_topic_id_fkey',              'timeline_pin_topic',           type_='foreignkey')
    op.drop_constraint('timeline_topic_subscriptions_topic_id_fkey',    'timeline_topic_subscriptions', type_='foreignkey')
    conn.execute(sa.text("CREATE SEQUENCE tmp_timeline_topics_id_seq"))
    op.add_column('timeline_topics', sa.Column('new_id', sa.INTEGER(), nullable=True))
    conn.execute(sa.text("UPDATE timeline_topics SET new_id = nextval('tmp_timeline_topics_id_seq')"))
    op.add_column('timeline_pin_topic',           sa.Column('new_topic_id',      sa.INTEGER(), nullable=True))
    op.add_column('timeline_topic_subscriptions', sa.Column('new_topic_id',      sa.INTEGER(), nullable=True))
    conn.execute(sa.text("""
        UPDATE timeline_pin_topic p
        SET    new_topic_id = t.new_id
        FROM   timeline_topics t
        WHERE  p.topic_id = t.id
    """))
    conn.execute(sa.text("""
        UPDATE timeline_topic_subscriptions s
        SET    new_topic_id = t.new_id
        FROM   timeline_topics t
        WHERE  s.topic_id = t.id
    """))
    op.drop_column('timeline_pin_topic',           'topic_id')
    op.drop_column('timeline_topic_subscriptions', 'topic_id')
    op.drop_constraint('timeline_topics_pkey', 'timeline_topics', type_='primary')
    op.drop_column('timeline_topics', 'id')
    op.alter_column('timeline_topics', 'new_id', new_column_name='id', nullable=False)
    op.alter_column('timeline_pin_topic',           'new_topic_id',      new_column_name='topic_id')
    op.alter_column('timeline_topic_subscriptions', 'new_topic_id',      new_column_name='topic_id')
    conn.execute(sa.text("ALTER SEQUENCE tmp_timeline_topics_id_seq OWNED BY timeline_topics.id"))
    conn.execute(sa.text("ALTER TABLE timeline_topics ALTER COLUMN id SET DEFAULT nextval('tmp_timeline_topics_id_seq')"))
    op.create_primary_key('timeline_topics_pkey', 'timeline_topics', ['id'])
    op.create_foreign_key('timeline_pin_topic_topic_id_fkey', 'timeline_pin_topic',
                          'timeline_topics', ['topic_id'], ['id'])
    op.create_foreign_key('timeline_topic_subscriptions_topic_id_fkey', 'timeline_topic_subscriptions',
                          'timeline_topics', ['topic_id'], ['id'])

    op.drop_constraint('app_glance_slices_app_glance_id_fkey',          'app_glance_slices',            type_='foreignkey')
    conn.execute(sa.text("CREATE SEQUENCE tmp_app_glances_id_seq"))
    op.add_column('app_glances',     sa.Column('new_id', sa.INTEGER(), nullable=True))
    conn.execute(sa.text("UPDATE app_glances     SET new_id = nextval('tmp_app_glances_id_seq')"))
    op.add_column('app_glance_slices',            sa.Column('new_app_glance_id', sa.INTEGER(), nullable=True))
    conn.execute(sa.text("""
        UPDATE app_glance_slices s
        SET    new_app_glance_id = g.new_id
        FROM   app_glances g
        WHERE  s.app_glance_id = g.id
    """))
    op.drop_column('app_glance_slices',            'app_glance_id')
    op.drop_constraint('app_glances_pkey',     'app_glances',     type_='primary')
    op.drop_column('app_glances',     'id')
    op.alter_column('app_glances',     'new_id', new_column_name='id', nullable=False)
    op.alter_column('app_glance_slices',            'new_app_glance_id', new_column_name='app_glance_id')
    conn.execute(sa.text("ALTER SEQUENCE tmp_app_glances_id_seq     OWNED BY app_glances.id"))
    conn.execute(sa.text("ALTER TABLE app_glances     ALTER COLUMN id SET DEFAULT nextval('tmp_app_glances_id_seq')"))
    op.create_primary_key('app_glances_pkey',     'app_glances',     ['id'])
    op.create_foreign_key('app_glance_slices_app_glance_id_fkey', 'app_glance_slices',
                          'app_glances', ['app_glance_id'], ['id'])
    # ### end Alembic commands ###
