"""add fcm_tokens table

Revision ID: c07e22596d37
Revises: de2ba13df54d
Create Date: 2026-03-07 02:06:23.878044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07e22596d37'
down_revision = 'de2ba13df54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.create_index('fcm_token_uid_token_index', ['user_id', 'token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.drop_index('fcm_token_uid_token_index')

    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
