"""Add shared timeline pins and subscriptions

Revision ID: d2fd4c10780d
Revises: d38ed87c5d5d
Create Date: 2025-11-09 02:35:32.021773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2fd4c10780d'
down_revision = 'd38ed87c5d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('app_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('timeline_topic_appuuid_name_index', 'timeline_topics', ['app_uuid', 'name'], unique=True)
    op.create_table('timeline_pin_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pin_id'], ['timeline_pins.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['timeline_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('timeline_pin_topic_pinid_topicid_index', 'timeline_pin_topic', ['pin_id', 'topic_id'], unique=True)
    op.create_table('timeline_topic_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['timeline_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_topic_subscriptions_user_id'), 'timeline_topic_subscriptions', ['user_id'], unique=False)
    op.create_index('timeline_topic_subscription_userid_topicid_index', 'timeline_topic_subscriptions', ['user_id', 'topic_id'], unique=True)
    op.alter_column('timeline_pins', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('user_timeline_pinid', table_name='user_timeline')
    op.create_index('user_timeline_userid_pinid', 'user_timeline', ['user_id', 'pin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_timeline_userid_pinid', table_name='user_timeline')
    op.create_index('user_timeline_pinid', 'user_timeline', ['pin_id'], unique=False)
    op.alter_column('timeline_pins', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('timeline_topic_subscription_userid_topicid_index', table_name='timeline_topic_subscriptions')
    op.drop_index(op.f('ix_timeline_topic_subscriptions_user_id'), table_name='timeline_topic_subscriptions')
    op.drop_table('timeline_topic_subscriptions')
    op.drop_index('timeline_pin_topic_pinid_topicid_index', table_name='timeline_pin_topic')
    op.drop_table('timeline_pin_topic')
    op.drop_index('timeline_topic_appuuid_name_index', table_name='timeline_topics')
    op.drop_table('timeline_topics')
    # ### end Alembic commands ###
