"""Change timeline object index around a bit.

Revision ID: d38ed87c5d5d
Revises: 6af0357ee34b
Create Date: 2019-11-06 01:07:54.199499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38ed87c5d5d'
down_revision = '6af0357ee34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_timeline_pinid', 'user_timeline', ['pin_id'], unique=True)
    op.drop_index('user_timeline_user_id', table_name='user_timeline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_timeline_user_id', 'user_timeline', ['user_id'], unique=False)
    op.drop_index('user_timeline_pinid', table_name='user_timeline')
    # ### end Alembic commands ###
