"""Implement AppGlances

Revision ID: de2ba13df54d
Revises: d2fd4c10780d
Create Date: 2025-05-29 18:12:57.654473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de2ba13df54d'
down_revision = 'd2fd4c10780d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_glances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('app_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('app_glance_userid_appuuid', 'app_glances', ['user_id', 'app_uuid'], unique=True)
    op.create_index(op.f('ix_app_glances_user_id'), 'app_glances', ['user_id'], unique=False)
    op.create_table('app_glance_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_glance_id', sa.Integer(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_glance_id'], ['app_glances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_glance_slices')
    op.drop_index(op.f('ix_app_glances_user_id'), table_name='app_glances')
    op.drop_index('app_glance_userid_appuuid', table_name='app_glances')
    op.drop_table('app_glances')
    # ### end Alembic commands ###
