"""Create FcmInstance table

Revision ID: e863e43d6570
Revises: bab1862ebd29
Create Date: 2026-10-01 16:06:50.034911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e863e43d6570'
down_revision = 'bab1862ebd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_instances',
    sa.Column('fid', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_index('fcm_instance_uid_fid_index', 'fcm_instances', ['user_id', 'fid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fcm_instance_uid_fid_index', table_name='fcm_instances')
    op.drop_table('fcm_instances')
    # ### end Alembic commands ###
