"""Create missing topic indexes

Revision ID: ebd468599212
Revises: e863e43d6570
Create Date: 2026-10-01 16:09:53.509816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebd468599212'
down_revision = 'e863e43d6570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('timeline_pin_topic_pinid_topicid_index', 'timeline_pin_topic', ['pin_id', 'topic_id'], unique=True)
    op.alter_column('timeline_topic_subscriptions', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('timeline_topic_subscription_userid_topicid_index', 'timeline_topic_subscriptions', ['user_id', 'topic_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('timeline_topic_subscription_userid_topicid_index', table_name='timeline_topic_subscriptions')
    op.alter_column('timeline_topic_subscriptions', 'id',
               existing_type=sa.Integer(),
               type_=postgresql.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('timeline_pin_topic_pinid_topicid_index', table_name='timeline_pin_topic')
    # ### end Alembic commands ###
